CV.Web/Controllers/AdminController.cs
using CV.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CV.Web.Controllers
{
    public class AdminController : BaseController
    {

        public ActionResult Database()
        {
            return View();
        }

        public ActionResult Upload()
        {
            return View(new FileListModel());
        }

        [HttpPost, Authorize]
        public ActionResult UploadFile()
        {
            if (!IsAdministrator)
                return Json("UNAUTHORIZED");

            try
            {
                if (Request.Files.Count > 0)
                {
                    var file = Request.Files[0];

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Content/images/custom", fileName);
                        file.SaveAs(path);
                    }
                }

                return Json("SUCCESS");
            }
            catch (Exception ex)
            {
                string error = HandleError(ex);
                return Json(string.Format("File upload failed! {0}", error));
            }
        }

        [Authorize]
        public ActionResult PrepareDatabase()
        {
            if (!IsAdministrator)
                return RedirectToIndex();

            try
            {
                CV.DataLayer.CVDbContext.DatabaseContext.CreateTablesWithCheck();
                ViewBag.Result = "SUCCESS";
            }
            catch ( Exception ex )
            {
                ViewBag.Result = ex.Message + "\r\n" + ex.StackTrace;
            }

            return View();
        }

    }
}

CV.Web/Controllers/CompanyController.cs
using CV.Web.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CV.Web.Controllers
{
    public class CompanyController : BaseController
    {
        /// <summary>
        /// Constructor
        /// </summary>
        public CompanyController()
        {
            UsesDatabase = true;
        }

        protected override string SetTitle(string action)
        {
            switch (action.ToLower())
            {
                case "index": return "Companies I Worked At";
                default: return base.SetTitle(action);
            }
        }

        #region Actions
        public ActionResult Index(int companyId =0)
        {
            return View(new CompanyListModel());
        }

        private CompanyModel GetCompanyInfo( int companyId )
        {
            CV.DataLayer.Company companyInfo = (from m in CV.DataLayer.CVDbContext.DatabaseContext.COMPANIES where m.ID == companyId select m).FirstOrDefault();
            if (companyInfo == null)
                throw new InvalidOperationException();

            CompanyModel companyInfoModel = new CompanyModel()
            {
                CompanyID = companyId,
                EndDate = companyInfo.EndYear,
                Link = companyInfo.Link,
                Name = companyInfo.Name,
                Positions = companyInfo.Positions,
                StartDate = companyInfo.StartYear
            };

            return companyInfoModel;
        }

        #endregion

        #region AJAX Calls/Queries

        /// <summary>
        /// Saves existing company
        /// </summary>
        /// <param name="companyId">Company id</param>
        /// <returns>View as result</returns>
        /// <remarks>Parameter is nullable because of return url crashes</remarks>
        [Authorize, HttpPost]
        public ActionResult Save(CompanyModel model)
        {
            if (!IsAdministrator) return RedirectToCompanyIndex();

            try
            {
                //: make some checks
                if (model == null)
                    return Json("Company instance is null. Something gone wrong!");

                //: check properties
                if (string.IsNullOrEmpty(model.Name)) return Json("Company Name cannot be left empty!");
                else if (string.IsNullOrEmpty(model.Positions)) return Json("Position info cannot be left empty!");
                else if (model.StartDate > DateTime.Today) return Json("Start date for position is invalid!");
                else if (model.EndDate.HasValue && model.EndDate > DateTime.Today) return Json("End date for position is invalid!");
                else if (model.EndDate.HasValue && model.EndDate < model.StartDate) return Json("End date for position is before Start date!");

                CV.DataLayer.Company companyData = null;
                if (model.CompanyID == 0)
                {
                    var otherCompanies = (from m in CV.DataLayer.CVDbContext.DatabaseContext.COMPANIES
                                          where m.Name == model.Name
                                          select m).Count();
                    if (otherCompanies > 0)
                        return Json("Another Company with same title exists!");

                    companyData = new DataLayer.Company();
                    CV.DataLayer.CVDbContext.DatabaseContext.COMPANIES.Add(companyData);
                }
                else
                {
                    companyData = (from m in CV.DataLayer.CVDbContext.DatabaseContext.COMPANIES
                                   where m.ID == model.CompanyID
                                   select m).FirstOrDefault();

                    if (companyData == null)
                        return Json("Company id is not valid, company not found!");
                }

                companyData.ID = model.CompanyID;
                companyData.EndYear = model.EndDate;
                companyData.Link = model.Link;
                companyData.Positions = model.Positions;
                companyData.StartYear = model.StartDate;
                companyData.Name = model.Name;

                CV.DataLayer.CVDbContext.DatabaseContext.SaveChanges();

                return Json("SUCCESS" + companyData.ID);
            }
            catch (Exception ex)
            {
                string error = HandleError(ex);
                return Json(string.Format("Company info saving failed! {0}", error));
            }
        }

        [HttpGet]
        public ActionResult ShowCompanyInfo(int companyId)
        {
            return PartialView("~/Views/Shared/DisplayTemplates/CompanyModel.cshtml", GetCompanyInfo(companyId));
        }

        [HttpGet, Authorize]
        public ActionResult EditCompanyInfo(int companyId)
        {
            return PartialView("~/Views/Shared/EditorTemplates/CompanyModel.cshtml", GetCompanyInfo(companyId));
        }

        [Authorize, HttpGet]
        public ActionResult New()
        {
            CompanyModel companyInfoModel = new CompanyModel() { CompanyID = 0, StartDate = DateTime.Today };

            return PartialView("~/Views/Shared/EditorTemplates/CompanyModel.cshtml", companyInfoModel);
        }

        [Authorize, HttpPost]
        public JsonResult Delete(int companyId)
        {
            if (!IsAdministrator) return Json("UNAUTHORIZED");

            try
            {
                var company = CV.DataLayer.CVDbContext.DatabaseContext.COMPANIES.Single(m => m.ID == companyId);
                if( company == null)
                    return Json("Company does not exist, invalid company ID!");

                //: remove contents
                var contents = from p in CV.DataLayer.CVDbContext.DatabaseContext.COMPANYINFO where p.OwnerId == companyId select p;
                foreach (CV.DataLayer.CompanyContent pi in contents)
                    CV.DataLayer.CVDbContext.DatabaseContext.COMPANYINFO.Remove(pi);

                //: remove project parts
                var projectContents = (from pc in CV.DataLayer.CVDbContext.DatabaseContext.PROJECTINFO
                                       join CV.DataLayer.Project p in CV.DataLayer.CVDbContext.DatabaseContext.PROJECTS on pc.OwnerId equals p.ID
                                       where p.CompanyId == companyId
                                       select pc);
                foreach( CV.DataLayer.ProjectContent pc in projectContents)
                    CV.DataLayer.CVDbContext.DatabaseContext.PROJECTINFO.Remove(pc);

                //: remove projects
                var project = from p in CV.DataLayer.CVDbContext.DatabaseContext.PROJECTS where p.CompanyId == companyId select p;
                foreach (CV.DataLayer.Project p in project)
                    CV.DataLayer.CVDbContext.DatabaseContext.PROJECTS.Remove(p);

                CV.DataLayer.CVDbContext.DatabaseContext.COMPANIES.Remove(company);

                CV.DataLayer.CVDbContext.DatabaseContext.SaveChanges();
                return Json("SUCCESS");
            }
            catch
            {
                return Json("FAILURE");
            }
        }
        #endregion

    }
}

CV.Web/Views/Shared/_Layout.cshtml
@{
    System.Globalization.CultureInfo culture = new System.Globalization.CultureInfo("en-US");
    string RAction = Convert.ToString(Request.RequestContext.RouteData.Values["action"]).ToLower(culture);
    string RController = Convert.ToString(Request.RequestContext.RouteData.Values["controller"]).ToLower(culture);
    bool isAdmin = (Html.ViewContext.Controller as CV.Web.Controllers.BaseController).IsAdministrator;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/common.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/panel.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/input.css")" />
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui-1.8.19.custom.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.blockUI.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/modernizr-1.7.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/common.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/date.js")"></script>
    @if (RController == "user")
    {
        <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/views/logon.css")" />
        switch (RAction)
        {
            case "logon":
                <script type="text/javascript" src="@Url.Content("~/Scripts/views/logon.js")"></script>
                break;
            case "deleteuser":
            case "register":
            case "changepassword":
            default:
                break;
        }
    }
    else if (RController == "company")
    {
        <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/views/content.css")" />
        <script type="text/javascript" src="@Url.Content("~/Scripts/views/company.js")"></script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/views/content.js")"></script>
    }
    else if (RController == "project")
    {
        <script type="text/javascript" src="@Url.Content("~/Scripts/views/project.js")"></script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/views/content.js")"></script>
    }
    else if (RController == "home" && RAction == "self")
    {
        <script type="text/javascript" src="@Url.Content("~/Scripts/views/content.js")"></script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/views/self.js")"></script>
        <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/views/content.css")" />
    }
</head>
<body>
    <div id="layoutwrap">
        <header>
            <div id="layouttitle">
                <div id="layouttitleinternal">
                    <h1>Information about Uğur Güngören</h1>
                </div>
            </div>
            <div id="layoutlogindisplay">
                @Html.Partial("_LoginPartial")
            </div>
            <nav>
                <table id="layoutmenutbl">
                    <tr>
                        <td align="left">
                            <ul id="layoutnavigation">
                                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                <li>@Html.ActionLink("Companies", "Index", "Company")</li>
                                <li>@Html.ActionLink("Commercial Projects", "CommercialProjects", "Project")</li>
                                <li>@Html.ActionLink("Personal Projects", "PersonalProjects", "Project")</li>
                                <li>@Html.ActionLink("Personal Info", "Self", "Home")</li>
                                <li>@Html.ActionLink("About", "About", "Home")</li>
                                @if (isAdmin)
                                {
                                    <li>@Html.ActionLink("Upload File", "Upload", "Admin")</li>
                                    <li>@Html.ActionLink("Create Database", "Database", "Admin")</li>
                                }
                            </ul>
                        </td>
                    </tr>
                </table>
            </nav>
        </header>
        <section id="layoutmain">
            @RenderBody()
        </section>
    </div>
    <footer>
        <p>All rights reserved to Ugur Gungoren. ©2017</p>
        <p>Contact: <a target="new" href="mailto:@CV.Web.Configuration.EmailAddress">@CV.Web.Configuration.EmailAddress</a>, <a target="new" href="@CV.Web.Configuration.Linkedin">Linkedin Profile</a> </p>
        <p>I don't have other social media accounts.</p> 
    </footer>
</body>
</html>

CV.Web/Views/Shared/_WaitPartial.cshtml
<div id="loading"><img src="@Url.Content("~/Content/images/loading.gif")" /></div>